"""Build a fully static version of the app — no backend, no cold start.

Every /api/* response the frontend uses is a pure function of two CSVs that
never change at runtime, so there is no reason to compute them per request on a
server that falls asleep. This script precomputes all of them, writes them next
to a patched copy of the UI, and the result can be dropped on GitHub Pages,
Vercel, Netlify or any static host.

Output layout (default: ./static):

    static/
      index.html            patched new_UI.html (fetch shim injected)
      data.json             directory + network + per-molecule records
      molblocks/<n>.json    3D coordinates, fetched lazily, one file each
      public/               copied through unchanged

Run from the repo root:   python scripts/build_static.py
"""

from __future__ import annotations

import json
import shutil
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import main  # noqa: E402  (imports after sys.path is set)

OUT_DIR = REPO_ROOT / "static"
MOLBLOCK_DIR = OUT_DIR / "molblocks"


# The frontend talks to the API through window.fetch. Rather than rewriting
# ~3,400 lines of frontend JS, we intercept /api/* and answer from the
# precomputed JSON. Everything else (including molblocks/<n>.json) passes
# straight through to the real fetch.
FETCH_SHIM = """
<!-- ============================================================
     STATIC MODE
     Answers the /api/* calls the UI makes from a precomputed data.json
     instead of a live FastAPI backend. Generated by scripts/build_static.py.
     ============================================================ -->
<script>
(function () {
  var DATA_URL = "data.json";
  var dataPromise = null;

  function loadData() {
    if (!dataPromise) {
      dataPromise = fetch(DATA_URL).then(function (r) {
        if (!r.ok) throw new Error("data.json " + r.status);
        return r.json();
      });
    }
    return dataPromise;
  }

  function json(body, status) {
    return new Response(JSON.stringify(body), {
      status: status || 200,
      headers: { "Content-Type": "application/json" }
    });
  }

  function audit(db, payload) {
    var items = (payload && payload.items) || [];
    var results = [];
    var failed = [];

    items.forEach(function (item) {
      var key = String(item.ingredient || "").toLowerCase().trim();
      var entry = db.molecules[key];
      var pct = item.percentage;

      if (!entry) {
        results.push({ status: "PASS", name: item.ingredient, formula_pct: pct,
                       limit: "N/A", risk: "Unregulated" });
        return;
      }

      var limit = Number(entry.limit);
      if (String(entry.status).indexOf("Banned") !== -1 || limit === 0) {
        results.push({ status: "FAIL", name: entry.name, formula_pct: pct,
                       limit: "BANNED", risk: entry.risk });
        failed.push(entry.name);
      } else if (pct > limit) {
        results.push({ status: "FAIL", name: entry.name, formula_pct: pct,
                       limit: limit + "%", risk: entry.risk });
        failed.push(entry.name);
      } else {
        results.push({ status: "PASS", name: entry.name, formula_pct: pct,
                       limit: limit + "%", risk: "Permissible" });
      }
    });

    return {
      filename: (payload && payload.filename) || "uploaded_formula.csv",
      results: results,
      compliant: failed.length === 0,
      failed_items: failed
    };
  }

  var nativeFetch = window.fetch.bind(window);

  window.fetch = function (input, init) {
    var raw = typeof input === "string" ? input : (input && input.url) || "";
    var parsed;
    try {
      parsed = new URL(raw, window.location.href);
    } catch (_) {
      return nativeFetch(input, init);
    }

    if (parsed.pathname.indexOf("/api/") !== 0) {
      return nativeFetch(input, init);
    }

    return loadData().then(function (db) {
      var path = parsed.pathname;

      if (path === "/api/directory") return json(db.directory);
      if (path === "/api/network") return json(db.network);
      if (path === "/api/health") {
        return json({ loaded_records: Object.keys(db.molecules).length,
                      mode: "static", generated_at: db.generated_at });
      }

      if (path === "/api/search") {
        var q = (parsed.searchParams.get("q") || "").toLowerCase();
        if (!q) return json([]);
        var hits = [];
        for (var key in db.molecules) {
          if (key.indexOf(q) === 0) hits.push({ name: db.molecules[key].name });
        }
        return json(hits);
      }

      if (path.indexOf("/api/molecule/") === 0) {
        var name = decodeURIComponent(path.slice("/api/molecule/".length)).toLowerCase();
        var found = db.molecules[name];
        if (!found) return json({ detail: "Molecule not found in database." }, 404);
        return json(found);
      }

      if (path === "/api/audit") {
        var body = {};
        try { body = JSON.parse((init && init.body) || "{}"); } catch (_) {}
        return json(audit(db, body));
      }

      return json({ detail: "Not available in static mode." }, 404);
    });
  };
})();
</script>
"""

# Anchor: the shim is injected immediately after the library <script> tags, so
# it is in place before the app's own inline script runs at the end of <body>.
ANCHOR = '<script defer src="https://cdn.jsdelivr.net/npm/vis-network@10.1.2/standalone/umd/vis-network.min.js"></script>'
LEGACY_ANCHOR = '<script src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>'


def slug(index: int) -> str:
    return f"{index:04d}"


def build() -> None:
    started = time.time()

    # Overwrite in place rather than wiping the directory: some environments
    # (sandboxed shells, read-only-ish mounts) can write but not unlink. Pass
    # --clean to force a fresh directory when you want stale files pruned.
    if "--clean" in sys.argv and OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    MOLBLOCK_DIR.mkdir(parents=True, exist_ok=True)

    stale = {p.name for p in MOLBLOCK_DIR.glob("*.json")}

    keys = list(main.MOCK_DB.keys())
    total = len(keys)
    print(f"Precomputing {total} molecule records…")

    molecules: dict[str, dict] = {}
    with_3d = 0

    for i, key in enumerate(keys):
        record = main.get_molecule_data(key, include_3d=False)

        mol_block = main.compute_molblock(record.get("smiles", "") or "")
        if mol_block:
            name = slug(i)
            (MOLBLOCK_DIR / f"{name}.json").write_text(
                json.dumps({"mol_block": mol_block}), encoding="utf-8"
            )
            record["mol_block_url"] = f"molblocks/{name}.json"
            stale.discard(f"{name}.json")
            with_3d += 1
        else:
            record["mol_block_url"] = None

        record["mol_block"] = None
        molecules[key] = record

        if (i + 1) % 50 == 0 or i + 1 == total:
            print(f"  {i + 1}/{total}  ({with_3d} with 3D coordinates)")

    payload = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "directory": main.get_directory(),
        "network": main.get_network(),
        "molecules": molecules,
    }
    (OUT_DIR / "data.json").write_text(json.dumps(payload), encoding="utf-8")

    html = (REPO_ROOT / "new_UI.html").read_text(encoding="utf-8")
    if ANCHOR in html:
        html = html.replace(ANCHOR, ANCHOR + "\n" + FETCH_SHIM, 1)
    elif LEGACY_ANCHOR in html:
        html = html.replace(LEGACY_ANCHOR, LEGACY_ANCHOR + "\n" + FETCH_SHIM, 1)
    else:
        raise SystemExit("Could not find the script-tag anchor in new_UI.html — "
                         "the shim would not be injected. Aborting.")
    (OUT_DIR / "index.html").write_text(html, encoding="utf-8")

    public_src = REPO_ROOT / "public"
    if public_src.is_dir():
        shutil.copytree(public_src, OUT_DIR / "public", dirs_exist_ok=True)

    if stale:
        print(f"\nNote: {len(stale)} molblock file(s) in the output are no longer "
              f"referenced (left in place). Run with --clean to prune.")

    data_kb = (OUT_DIR / "data.json").stat().st_size / 1024
    mol_kb = sum(f.stat().st_size for f in MOLBLOCK_DIR.glob("*.json")) / 1024
    html_kb = (OUT_DIR / "index.html").stat().st_size / 1024

    print()
    print(f"Wrote {OUT_DIR.relative_to(REPO_ROOT)}/ in {time.time() - started:.1f}s")
    print(f"  index.html   {html_kb:8.1f} KB   (loaded on first paint)")
    print(f"  data.json    {data_kb:8.1f} KB   (loaded on first paint)")
    print(f"  molblocks/   {mol_kb:8.1f} KB across {with_3d} files (lazy, one per molecule)")


if __name__ == "__main__":
    build()
